name: Build and Deploy JAR (Dev)

on:
  push:
    branches: [ "Dev" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Permitir ejecución de Maven wrapper
        run: chmod +x mvnw

      - name: Compilar JAR
        run: ./mvnw clean package -DskipTests

      - name: Ejecutar JAR
        run: |
          mkdir -p /opt/apps/
          cp target/docmanager-0.0.1.jar /opt/apps/
          pkill -f docmanager-0.0.1.jar || true
          nohup java -jar /opt/apps/docmanager-0.0.1.jar > /opt/apps/app-dev.log 2>&1 &
