name: Build and Deploy JAR (Dev)

on:
  push:
    branches: [ "Dev" ]  # <- activa el workflow solo con push en Dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set execute permission for mvnw
      run: chmod +x mvnw

    - name: Construir el JAR
      run: ./mvnw clean package -DskipTests

    - name: Copiar JAR al servidor (entorno Dev)
      uses: appleboy/sftp-action@v0.0.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: target/docmanager-0.0.1.jar
        target: /opt/docmanager-dev/

    - name: Reiniciar aplicación remotamente (entorno Dev)
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pkill -f docmanager-0.0.1.jar || true
          nohup java -jar /opt/docmanager-dev/docmanager-0.0.1-SNAPSHOT.jar > /opt/docmanager-dev/app-dev.log 2>&1 &
